### ISSUE TITLE
ui: remove material-ui deprecation warnings

### ISSUE THREAD

**Issue by dctalbot** [target/goalert#1762]
**What problem would you like to solve? Please describe:**
Material-UI is [upgrading to v5](https://next.material-ui.com/guides/migration-v4/) and has introduced deprecation warnings that are quite noisy in the console

**Describe the solution you'd like:**
Use the codemods provided [here](https://github.com/mui-org/material-ui/tree/HEAD/packages/material-ui-codemod#moved-lab-modules) to remove warnings where possible. Otherwise, manually resolve remaining warnings.

- [x] ```createMuiTheme function was renamed to createTheme``` (#1775)
- [x] ```The prop `justify` of `ForwardRef(Grid)` is deprecated. Use `justifyContent` instead, the prop was renamed.``` (#1768)
- [x] Dialog: ```The prop `disableBackdropClick` of `ForwardRef(Dialog)` is deprecated. Use the onClose prop with the `reason` argument to filter the `backdropClick` events.``` (#1786)
- [x] Dialog: ```The prop `onExited` of `ForwardRef(Dialog)` is deprecated. Use the `TransitionProps` prop instead.``` (#1800)
- [x] Mobile: ```The prop `onEscapeKeyDown` of `ForwardRef(Modal)` is deprecated. Use the onClose prop with the `reason` argument to handle the `escapeKeyDown` events.``` (#1813)
- [x] ~~Temp Sched: ```The `fade` color utility was renamed to `alpha` to better describe its functionality.```~~ (https://github.com/mui-org/material-ui-pickers/issues/2200)

**Describe alternatives you've considered:**
I think [they have a release](https://www.npmjs.com/package/@material-ui/core/v/4.11.3-deprecations.1) that is identical but has the warnings stripped away. If we decide we aren't interested in upgrading to v5 any time soon then this is a good option.

Example warning:
<img width="875" alt="Screen Shot 2021-07-15 at 10 54 50 AM" src="https://user-images.githubusercontent.com/17692467/125819738-1f0fb4fb-d1d1-486e-95b3-55083255bfa4.png">

**Comment by NateBigStone** [comment]
David, may I take on this task ? @dctalbot

**Comment by dctalbot** [comment]
@NateBigStone sure! I'm going to break this issue into a task list so we can do one pull request per codemod. That will help with review and let us work in parallel if needed. Once the new issues are created, let me know which one(s) you would like to work on

**Comment by dctalbot** [comment]
Actually, I just found out they have one codemod specifically made for migrating: https://github.com/mui-org/material-ui/tree/HEAD/packages/material-ui-codemod#-preset-safe

Assuming it works, resolving this issue should be as simple as running 
```
npx @material-ui/codemod@next v5.0.0/preset-safe <path|folder>
```

**Comment by NateBigStone** [comment]
Cool @dctalbot,
I had issues with the create them one, but 
```
npx @material-ui/codemod@next v5.0.0/grid-justify-justifycontent web
```
Seemed to work like a charm

https://github.com/NateBigStone/goalert/tree/mui-justify-content

**Comment by NateBigStone** [comment]
I can circe back to the `createMuiTheme function was renamed to createTheme` task

**Comment by NateBigStone** [comment]
@dctalbot for `disableBackdropClick`, the codemod simple removes it, but looking at
https://next.material-ui.com/guides/migration-v4/#dialog , I'm not sure if I'm on the right track to maintain the same functionality 
https://github.com/target/goalert/compare/master...NateBigStone:disable-backdrop-click-warning?expand=1

**Comment by dctalbot** [comment]
@NateBigStone definitely on the right track! Feel free to open a PR and we can walk through any necessary changes. See if you can get those `onClose` handlers down to just one `if` statement each:

```js
onClose={(event, reason) => {
  if (satisfying condition) {
    perform close
  }
}}
```

If you're familiar with De Morgan's law, that may come in handy :)

**Comment by NateBigStone** [comment]
>`onEscapeKeyDown`
The way this is being used, is the default behavior of the drawer that escape key exits, and onExit takes care of this?

https://github.com/target/goalert/blob/0678096a01994e397697ea8f83147e12b1839949/web/src/app/main/App.js#L103

**Comment by NateBigStone** [comment]
@dctalbot I'm having trouble recreating or finding `fade` for the
```The `fade` color utility was renamed to `alpha` to better describe its functionality.``` warning
Was this addressed already?

**Comment by dctalbot** [comment]
> > `onEscapeKeyDown`
> > The way this is being used, is the default behavior of the drawer that escape key exits, and onExit takes care of this?
> > Is it redundant ?
> 
> https://github.com/target/goalert/blob/0678096a01994e397697ea8f83147e12b1839949/web/src/app/main/App.js#L103

@NateBigStone Yes, its usage on the navigation drawer is redundant. We can simply remove the prop in that case.

**Comment by dctalbot** [comment]
> @dctalbot I'm having trouble recreating or finding `fade` for the
> `` The `fade` color utility was renamed to `alpha` to better describe its functionality. `` warning
> Was this addressed already?

I apologize, it looks like this is an issue with one of our dependencies (see https://github.com/mui-org/material-ui-pickers/issues/2200). It has been marked as a `wontifx` so we will have to live with it until material v5 comes out. Thanks for looking into it!

**Comment by dctalbot** [comment]
Thanks for all the help! @NateBigStone

**Comment by NateBigStone** [comment]
No problem! Good times @dctalbot ! I'll keep my eyes open for another one if I have some extra bandwidth in the near future
