### ISSUE TITLE
ui/theme: Semantic/Component Updates

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2214]
Need to update several components to maintain consistency and accessibility across light and dark modes.

- [x] outgoing message logs text field type: use outline, be consistent with search textfield (#2322)
- [x] schedule calendar event colors: (#2247)
    - All shifts: primary (no matter the type)
    - Override/Temp schedule header shift: secondary
- [x] calendar outline in dark mode: dark grey (#2247)
- [x] red badge color in ep form: secondary (#2243)
- [x] link color (text displayed with underline): secondary (#2229)
- [x] MUI Link component in our AppLink instead of a raw anchor tag (#2229)
- [x] copy text button color: primary (#2239)
- [x] open in new tab icon color: primary (#2239)
- [x] IconButton default color: primary (#2239)
- [x] highlighted item color: mark user as 'selected' with ListItem, use secondary (#2238)
- [x] loading items in FlatList: use skeleton from @mui (#2221)

---

from material design guidelines:

primary colors
- top app bar
- contained, text, and outlined buttons

secondary colors (optional, use sparingly to accent select parts of UI)
- FAB buttons
- Selection controls (sliders, switches, toggles, etc)
- Highlighting selected text
- Progress bars
- Links
- Headlines

---

Palettes to test
- New primary color: `blueGrey[400]` (#78909c)
  - light: #a7c0cd
  - dark: #4b636e
- New secondary color: `red[800]` (#c62828) - concern here with having red links, may not be easy to stay WCAG compliant
  - light: #ff5f52
  - dark: #8e0000
