### ISSUE TITLE
ui: convert remaining class components to hooks

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#923]
This is an issue to track progress on converting the remaining class components to React hooks.

They should be converted in javascript for review purposes (continue to use `PropTypes`). A separate issue will be created for converting to typescript if needed.

Decorators should also be removed. There is usually a corresponding hook to achieve the same functionality. 
For example, a class component using `@withWidth` and `props.width` can be written as a functional component that uses `const width = useWidth()`

Please keep PR size small, and run tests locally, to help speed up reviews.

- [x] app/admin/AdminDialog.js: AdminDialog (#996)
- [x] app/alerts/components/AlertDetails.js: AlertDetails (#997)
- [x] app/alerts/components/AlertsListControls.js: AlertsListControls (#998)
- [x] app/alerts/components/AlertsListFilter.js: AlertsListFilter (#999)
- [x] app/alerts/components/UpdateAlertsSnackbar.js: UpdateAlertsSnackbar (#1000)
- [x] app/alerts/pages/AlertDetailPage.js: AlertDetailPage (#1001)
- [x] app/dialogs/components/DialogContentError.js: DialogContentError (@KatieMSB #1004)
- [x] app/dialogs/components/DialogTitleWrapper.js: DialogTitleWrapper (@KatieMSB #1005)
- [x] ~~app/dialogs/components/DropDownMenu.js: DropdownMenu~~ (@KatieMSB #1156)
- [x] app/dialogs/FormDialog.js: FormDialog (@dctalbot  #1236)
- [x] app/documentation/components/IntegrationKeyAPI.js: IntegrationKeyAPI (@pnengchu https://github.com/target/goalert/pull/1020)
- [x] app/error-pages/Errors.js: GenericError (@KatieMSB #1009)
- [x] app/error-pages/Errors.js: ObjectNotFound (@KatieMSB #1009)
- [x] app/error-pages/Errors.js: PageNotFound (@KatieMSB #1009)
- [x] app/escalation-policies/PolicyCreateDialog.js: PolicyCreateDialog (@KatieMSB #1013)
- [x] app/escalation-policies/PolicyEditDialog.js: PolicyEditDialog (@KatieMSB #1016)
- [x] app/escalation-policies/PolicyForm.js: PolicyForm (@KatieMSB #1017)
- [x] app/escalation-policies/PolicyServicesCard.js: PolicyServicesCard (@KatieMSB #1022)
- [x] app/escalation-policies/PolicyServicesQuery.js: PolicyServicesQuery (@KatieMSB #1023)
- [x] app/escalation-policies/PolicyStepCreateDialog.js: PolicyStepCreateDialog (@KatieMSB #1041)
- [x] app/escalation-policies/PolicyStepDeleteDialog.js: PolicyStepDeleteDialog (@KatieMSB #1042)
- [x] app/escalation-policies/PolicyStepEditDialog.js: PolicyStepEditDialog (@KatieMSB #1043)
- [x] app/escalation-policies/PolicyStepForm.js: PolicyStepForm (@KatieMSB #1048)
- [x] app/escalation-policies/PolicyStep.js: PolicyStep (@KatieMSB #1049)
- [x] app/escalation-policies/PolicyStepsCard.js: PolicyStepsCard (@KatieMSB #1050)
- [x] app/escalation-policies/PolicyStepsQuery.js: PolicyStepsQuery (@KatieMSB #1051)
- [ ] app/forms/FormContainer.js: FormContainer (@tony-tvu  #2427)
- [x] app/forms/FormField.js: FormField (@KatieMSB #1653)
- [x] app/forms/Form.js: Form (@pnengchu https://github.com/target/goalert/pull/1008)
- [x] app/icons/components/Icons.js: Add (@pnengchu https://github.com/target/goalert/pull/1030)
- [x] app/icons/components/Icons.js: Slack (@pnengchu https://github.com/target/goalert/pull/1030)
- [x] app/icons/components/Icons.js: SlackBW (@pnengchu https://github.com/target/goalert/pull/1030)
- [x] app/icons/components/Icons.js: Trash (@pnengchu https://github.com/target/goalert/pull/1030)
- [x] app/icons/components/Icons.js: Warning (@pnengchu https://github.com/target/goalert/pull/1030)
- [x] app/lists/FlatList.js: FlatList (#982)
- [x] app/loading/components/LoadingButton.js: LoadingButton (@kanish671 #1451)
- [x] app/main/App.js: App (@dctalbot #1010)
- [x] app/main/components/SideBarDrawerList.js: SideBarDrawerList (@dctalbot #1021)
- [x] app/main/components/ToolbarAction.js: ToolbarAction (@dctalbot #1077)
- [x] app/main/components/ToolbarTitle.js: NameLoader (@KatieMSB #1316)
- [x] app/main/components/ToolbarTitle.js: ToolbarTitle (@KatieMSB #1316)
- [x] ~~app/main/ErrorBoundary.js: ErrorBoundary~~ (#1844)
- [x] ~~app/main/MobileSideBar.js: MobileSideBar~~ (@dctalbot #1170)
- [x] ~~app/main/URLErrorDialog.js: URLErrorDialog (@dctalbot #2039)
- [x] app/main/WideSideBar.js: WideSideBar (@dctalbot #1076)
- [x] app/rotations/RotationAddUserDialog.js: RotationAddUserDialog (@kanish671 #1452)
- [x] app/rotations/RotationCreateDialog.js: RotationCreateDialog (@kanish671 #1453)
- [x] app/rotations/RotationSetActiveDialog.js: RotationSetActiveDialog (@kanish671 #1454)
- [x] app/rotations/RotationUserDeleteDialog.js: RotationUserDeleteDialog (@kanish671 #1455)
- [x] app/rotations/RotationUserList.js: RotationUserList (@kanish671, @dctalbot #1499)
- [x] app/schedules/CalendarEventWrapper.js: CalendarEventWrapper
- [x] app/schedules/ScheduleAssignedToList.js: ScheduleAssignedToList (@voromahery #1695)
- [x] app/schedules/ScheduleCalendar.js: ScheduleCalendar
- [x] app/schedules/ScheduleCalendarQuery.js: ScheduleCalendarQuery
- [x] app/schedules/ScheduleCreateDialog.js: ScheduleCreateDialog (#1690)
- [x] app/schedules/ScheduleEditDialog.js: ScheduleEditDialog (@voromahery #1701)
- [x] app/schedules/ScheduleForm.js: ScheduleForm (#1696)
- [x] app/schedules/ScheduleNewOverrideFAB.js: ScheduleNewOverrideFAB (@voromahery #1704)
- [x] app/schedules/ScheduleOverrideDeleteDialog.js: ScheduleOverrideDeleteDialog (#1725)
- [x] app/schedules/ScheduleOverrideEditDialog.js: ScheduleOverrideEditDialog (#1769)
- [x] app/schedules/ScheduleOverrideList.js: ScheduleOverrideList (#1571)
- [x] app/schedules/ScheduleRouter.js: ScheduleList (#1727)
- [x] app/schedules/ScheduleRouter.js: ScheduleRouter
- [x] app/schedules/ScheduleRuleDeleteDialog.js: ScheduleRuleDeleteDialog (@ganamavo #1717)
- [ ] app/schedules/ScheduleRuleEditDialog.js: ScheduleRuleEditDialog (#1792)
- [x] app/schedules/ScheduleRuleForm.js: ScheduleRuleForm (#1730)
- [x] app/schedules/ScheduleRuleList.js: ScheduleRuleList (@KatieMSB #1620)
- [x] app/schedules/ScheduleShiftList.js: ScheduleShiftList (@dctalbot  #1027)
- [x] app/services/IntegrationKeyCreateDialog.js: IntegrationKeyCreateDialog (#1734)
- [x] app/services/ServiceLabelDeleteDialog.js: ServiceLabelDeleteDialog (#1749)
- [x] app/services/ServiceLabelEditDialog.js: ServiceLabelCreateDialog (#1750)
- [x] app/services/ServiceLabelForm.js: LabelForm (@phoenix6561 #1289)
- [x] app/services/ServiceLabelList.js: ServiceLabelList (#1752)
- [x] app/users/UserContactMethodDeleteDialog.js: UserContactMethodDeleteDialog(@alejandra-martinez #1024)
- [x] app/users/UserContactMethodEditDialog.js: UserContactMethodEditDialog (#1731)
- [x] app/users/UserContactMethodForm.js: UserContactMethodForm
- [x] app/users/UserContactMethodSelect.js: UserContactMethodSelect (#1742)
- [x] app/users/UserNotificationRuleCreateDialog.js: UserNotificationRuleCreateDialog (#1746)
- [x] app/users/UserNotificationRuleDeleteDialog.js: UserNotificationRuleDeleteDialog (#1747)
- [x] app/users/UserNotificationRuleForm.js: UserNotificationRuleForm (#1748)
- [x] app/users/UserNotificationRuleList.js: UserNotificationRuleList (#1751)
- [x] app/users/UserStatusUpdatePreference.js: UserStatusUpdatePreference (#1753)
- [x] app/util/AppBarSearchContainer.js: SearchProvider (#1842)
- [x] app/util/AppBarSearchContainer.js: SearchUpdater (#1843)
- [x] ~~app/util/Chips.js: PolicyChip~~ (@dctalbot  #1231)
- [x] app/util/Chips.js: RotationChip (@dctalbot  #1231)
- [x] app/util/Chips.js: ScheduleChip (@dctalbot  #1231)
- [x] app/util/Chips.js: SlackChip (@dctalbot  #1231)
- [x] app/util/Chips.js: UserChip (@dctalbot  #1231)
- [x] app/util/CountDown.js: CountDown (@dctalbot #1100)
- [x] app/util/FilterContainer.js: FilterContainer (@dctalbot #1078)
- [x] app/util/GoogleAnalytics.js: GoogleAnalytics #1884
- [x] ~~app/util/gracefulUnmount.js: GracefulUnmounter~~
- [x] ~~app/util/gracefulUnmount.js: GracefulUnmounterProvider~~
- [x] app/util/Markdown.js: Markdown (@dctalbot #1290)
- [x] app/util/MountWatcher.js: MountWatcher #1885 
- [x] ~~app/util/Options.js: Options~~ #1886
- [x] app/util/OtherActionsDesktop.js: OtherActionsMenuDesktop (@Voninkazo #1702)
- [x] app/util/OtherActions.js: OtherActions (#1700)
- [x] app/util/OtherActionsMobile.js: OtherActionsMenuMobile (@Voninkazo #1716)
- [x] app/util/PageActions.js: PageActionContainer (@kanish671 #1255)
- [x] app/util/PageActions.js: PageActionProvider (@kanish671 #1255)
- [x] app/util/PageActions.js: PageActions (@kanish671 #1255)
- [x] app/util/PageActions.js: PageActionUpdater (@kanish671 #1255)
- [x] ~~app/util/Query.js: Query~~ (deprecated)
- [x] app/wizard/WizardForm.js: WizardForm (#1791)
- [x] app/wizard/WizardRouter.js: WizardRouter (#1689)
- [x] app/wizard/WizardScheduleForm.js: WizardScheduleForm (#1770)

**Comment by Patil2099** [comment]
Can I work on this @mastercactapus?

**Comment by mastercactapus** [comment]
@Patil2099 absolutely!

I think what would be easiest is if you had a file or two in mind from the list and I can put your name by it so others know it's being worked on.

**Comment by kanish671** [comment]
I am interested in contributing. Can I pick `utils/PageActions`? If it's all fine I can do the changes for more components

**Comment by m17ch** [comment]
@kanish671 Absolutely!  I'll put your name next to the components so people will know you're working on them.  Thank you!

**Comment by kanish671** [comment]
Just to be sure, should I be pushing changes to my fork first or can I create branches directly in the main repo? Also, is there a branch naming strategy? I did not find answers to these in the contributing docs.

**Comment by m17ch** [comment]
@kanish671 -- You'll need at least Go `1.15+` to fix the error, which was when [they added the embedded tzdata package](https://golang.org/doc/go1.15).  I'm using `1.15.5` but latest should be fine (currently `1.15.7`).  I will update our development guide to include this major version requirement -- thanks for bringing it up.

I'd recommend on your fork, creating a new branch for the work (that you'll use as the base of the PR):  The branch name convention has been `hooks-<thing>` (can spot check a few other PRs above).

Let me know if you need anything else, or [hop in our Slack channel](https://github.com/target/goalert#contact-us) for more rapid back-and-forth.

**Comment by kanish671** [comment]
I'd like to take up a few more components for conversion.
```
app/loading/components/LoadingButton.js
app/rotations/RotationAddUserDialog.js
app/rotations/RotationCreateDialog.js
app/rotations/RotationSetActiveDialog.js
app/rotations/RotationUserDeleteDialog.js
app/rotations/RotationUserList.js
```

**Comment by dctalbot** [comment]
@kanish671 Sure, I will update the list to mark PageActions as complete and put your name by those components you listed. Thanks!

**Comment by ganamavo** [comment]
Hello,
My apology, I have been working on the WizardForm and it's already done but I didn't know that I need to ask first. I anyone can put my name next to it, that would be great. Can I work on WizardScheduleForm now?

**Comment by voromahery** [comment]
Could anyone put my name next to FormContainer, ScheduleAssignToList and ScheduleForm to let everyone know that I have worked on those issue, please? Thank you in advance!

**Comment by voromahery** [comment]
Hello everyone,

Could anyone put my name next to the FormContainer, ScheduleAssignToList and ScheduleForm to let evryone know that those components is being worked on, please?
Thank you in advance.

**Comment by ganamavo** [comment]
Now, I am working on ScheduleList. Can anyone put my name next to it with WizardForm and WizardScheduleForm because I have worked on them.
Thanks

**Comment by Voninkazo** [comment]
Hello all,

I have worked on the wizardRouter and Options components and they're actually.
And now I'm working on the util/OthereActions component.
Could anyone please put my name there.

Thank you!

**Comment by voromahery** [comment]
Thank you so much for everything. We are very happy to contribute.

**Comment by Voninkazo** [comment]
@Forfold I have made some changes on these following pull requests. 
Any suggestions will be appreciated :)
https://github.com/target/goalert/pull/1716
https://github.com/target/goalert/pull/1702
https://github.com/target/goalert/pull/1700
https://github.com/target/goalert/pull/1689

Thanks!

**Comment by Voninkazo** [comment]
@Forfold  We've worked on those tasks above but our names are not there yet, please add our names next to each task for people to know. Thanks :)

**Comment by Voninkazo** [comment]
@dctalbot Thank you for reviewing the code. I'm thinking of installing use-force-update dependency and import the useForceUpdate hook like this [example](https://bestofreactjs.com/repo/CharlesStover-use-force-update-react-awesome-react-hooks) Is that fine?

Thank you in advance!

**Comment by mastercactapus** [comment]
Closing as complete, the remaining work is captured in #3043 and #3044
